name: Workflow generator
'on':
  push:
    branches:
      - main
    paths:
      - .github/workflow-generator.yml
  pull_request:
    paths:
      - .github/workflow-generator.yml
  schedule:
    - cron: 0 10 * * *
  repository_dispatch:
    types:
      - workflow-generator
  workflow_dispatch: null
env:
  YTT_REPO: kirinus/.github
jobs:
  create-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v2
        with:
          path: this
      - name: Checkout ${{ env.YTT_REPO }} git repository
        uses: actions/checkout@v2
        with:
          path: remote
          ref: main
          repository: ${{ env.YTT_REPO }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: ytt
      - name: Generate Workflow
        uses: darioblanco/workflow-generator@main
        with:
          outputFiles: this/.github/workflows
          templatePaths: remote/ytt
          token: ${{ github.token }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: Flexo <83774503+kirinusbot@users.noreply.github.com>
          branch: ci/create-workflows
          base: main
          body: |
            Workflows automatically generated by the [workflow-generator](https://github.com/darioblanco/workflow-generator) GitHub action.
            - [Original Templates](https://github.com/kirinus/.github/tree/main/ytt)
            - [Action Versions](https://github.com/kirinus/.github/blob/main/ytt/data/versions.yaml)
          commit-message: 'ci: change github actions workflows'
          delete-branch: true
          labels: ci
          path: this
          title: 'ci: change github actions workflows'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
